### ISSUE TITLE
Stock Data

### ISSUE THREAD

**Issue by yevonnaelandrew** [efJerryYang/worldquant-brain-simulator#5]
Hello!

I'd like to experiment with the code, but it appears that the stock data is missing. Could you kindly upload the necessary data or guide me on how to acquire it? Thank you.

**Comment by efJerryYang** [comment]
Thank you for your interest in this project! To access the data, please send me an email requesting a share link
for Google Drive. Please note that the data will be compressed using the `tar.gz` format and there are already known problems with the data.

**Comment by yevonnaelandrew** [comment]
Thanks, noted. I just sent you an email.

**Comment by hif-dsai** [comment]
I'm also interested in experimenting with this project. Could you please provide me with the data? Thank you
