### ISSUE TITLE
Code for GLB alpha

### ISSUE THREAD

**Issue by Happy8945** [efJerryYang/worldquant-brain-simulator#7]

**Comment by efJerryYang** [comment]
@Happy8945 Hey, thanks for your interest in this project. It's not actively maintained, and I only make occasional contributions, so apologize for the delayed response.

For the GLB market, you'll need to obtain the data to get started. The data used for testing this project was scraped from public websites, and at the time of the project's creation, that scraping script was able to collect data only from China and the USA. Unfortunately, I cannot help with the data issue, so you'll need to source the data yourself or wait until I have a plan for testing other markets in this project.
